namespace WebApi.Entities;
// 134
public enum HandlingUnitType { // total 134
    AMM = 120, 
    BAG, BAL, BRG, BSK, BBL, BEM, BIC, BIN,
    BOB, BOT, BOX, BXI, BXT, BLK, BKG, BDL,
    CAB, CAG, CAN, CCS, CBY, CAR, CTN, CAS,
    CSK, CHE, CHS, COL, CON, CNX, CNT, CND,
    CNB, CNC, CBC, CRD, CRT, CUB, CYL, DRK,
    DSK, DTB, DRM, DBK, DUF, SKE, CNE, ENV,
    FIR, FSK, FLO, FWR, FRM, GOH, HRK, HTB,
    HPR, HED, HGH, HPT, CNA, TLD, JAR, JUG,
    KEG, KIT, KRK, KTB, LVN, LIF, SBC, LBK,
    FLX, LOG, LSE, LUG, MSV, MLV, MXD, CNF,
    MRP, NOL, HRB, WHE, OVW, PKG, PCK, PAL,
    PLS, PLT, PCS, PIR, PLN, PRK, PLF, POV,
    QTR, RCK, CLD, REL, RVR, ROL, SAK, TSS,
    SVN, RAL, SHT, SHK, SID, SKD, SLV, SLP,
    SPI, SPL, SCS, TNK, TKR, TKT, TRC, TBN,
    TTC, TRY, TRI, TRU, TRK, TUB, TBE, UNP,
    UNT, VPK, VEH, WLC, WRP 
}